### ISSUE TITLE
Is it slow to open or it's just me?

### ISSUE THREAD

**Issue by spidgorny** [Ahmadre/FlutterIconPicker#1]
Great widget. Exactly what I need.
It's a little slow to start. The app freezes for 1-2 seconds before the the popup appears.
My device is OnePlus 3T.
Is it going in a loop generating all the icons every time?
Could we pre-generate an array of icons and put as a const array in dart file?

**Comment by Ahmadre** [comment]
Thank you for filing this issue.

I also encountered this issue. Glad that I was not alone. Thank you also for the suggestion. Did you test it? Does it work with const? I can't test it now, but any PR's are very welcome :)

Best regards
Rebar

**Comment by Ahmadre** [comment]
Ok, I am working on a solutions. Already set const, but I have to render the InkResponse async

**Comment by Ahmadre** [comment]
Alright, new release is online. Just try it out and let me know :)

**Comment by Ahmadre** [comment]
![](https://i.imgur.com/o3F6C57.gif)

As you can see the picker is loading directly. You have to build a release app. closing this issue due to it's loading now directly

**Comment by spidgorny** [comment]
Thank you for a quick feedback and a fix. 
Version 1.1.5 is still slow for me. Maybe it's just my device performance.
