### ISSUE TITLE
IconManager.getSelectedPack() should include the customIconPack option

### ISSUE THREAD

**Issue by MasiaVittorio** [Ahmadre/FlutterIconPicker#11]
The search bar replaces the <String,IconData> map with the just material icons if the icon picker has a customIconPack, making the use of custom icon packs useless without a properly functioning search bar.

That is because IconManager.getSelectedPack returns "icons" if the IconPack enum is IconPack.custom

**Comment by Ahmadre** [comment]
Very good! Thank you for the Bug-Report!

I'll solve that asap!

I'll let you know here if an update came online :).

Best regards

**Comment by MasiaVittorio** [comment]
Thank you for the quick response!
I'm digging your package very much :D

**Comment by Ahmadre** [comment]
Fixed: [![Version](https://img.shields.io/badge/pub-v2.1.4-blue)](https://pub.dev/packages/flutter_iconpicker) :)
