### ISSUE TITLE
How do i use my own iconpack?

### ISSUE THREAD

**Issue by frederikw03** [Ahmadre/FlutterIconPicker#14]
I tried creating a icon pack. and i want it as my 'customIconPack', but i don't understand this explanation:
    /// Provide here your custom IconPack in a [Map<String, IconData>]
    /// to show your own collection of Icons to pick from

can you give me more detail on what to do after i changed my iconPackMode to custom? 
thanks

**Comment by frederikw03** [comment]
@Ahmadre Can you help me with this? Thanks

**Comment by Ahmadre** [comment]
There's an example file in /example folder. Have a look there :)

**Comment by frederikw03** [comment]
thanks, i got it to work 👍
