### ISSUE TITLE
Remove search?

### ISSUE THREAD

**Issue by frederikw03** [Ahmadre/FlutterIconPicker#15]
Hey, i want to remove the searchbar, because my iconpack is so small. Is it possible?

**Comment by frederikw03** [comment]
@Ahmadre :) Is this possible?

**Comment by Ahmadre** [comment]
@frederikw03 sure it's possible. You can fork it, but I can give ab parameter for that. I'll do that as soon as I've time :)

**Comment by frederikw03** [comment]
@Ahmadre thanks, ill be looking forward to it.

**Comment by Ahmadre** [comment]
Fixed. Will come with the new update 👍 
![Uploading Bildschirmfoto 2020-10-24 um 15.54.47.png…]()

**Comment by Ahmadre** [comment]
Fixed, will come with the new update :)
<img width="1185" alt="Bildschirmfoto 2020-10-24 um 15 54 47" src="https://user-images.githubusercontent.com/18512224/97083591-574f4500-1611-11eb-9a09-f372127fc65d.png">

**Comment by Ahmadre** [comment]
New version is published: [![Version](https://img.shields.io/badge/pub-v2.2.1-blue)](https://pub.dev/packages/flutter_iconpicker)
