### ISSUE TITLE
Adobe icon not available in FontAwesome 5.15, fails compile

### ISSUE THREAD

**Issue by nstrelow** [Ahmadre/FlutterIconPicker#16]
https://github.com/fluttercommunity/font_awesome_flutter/pull/124

This PR removed the Adobe icon, which now fails my build, even though I am not using that icon.

I suggest fixing the version of font_awesome_flutter to `8.8.1` until you add all the new icons and remove the old ones.

Error:
```
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:16:29: Error: Getter not found: 'adobe'.
  'adobe': FontAwesomeIcons.adobe,
                            ^^^^^
```

**Comment by merskip** [comment]
Hello,
I have the same problem and I created pull request which should fix this issue: https://github.com/Ahmadre/FlutterIconPicker/pull/17

**Comment by BermyToiga** [comment]
I also am having this problem. Just commented the adobe line out for now

**Comment by anderson-oki** [comment]
I have the same issue. I downgrade my `font_awesome_flutter` to `8.8.1` as temporary workaround.

**Comment by CiriousJoker** [comment]
```
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:16:29: Error: Getter not found: 'adobe'.
  'adobe': FontAwesomeIcons.adobe,
                            ^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:573:43: Error: Getter not found: 'fontAwesomeLogoFull'.
  'fontAwesomeLogoFull': FontAwesomeIcons.fontAwesomeLogoFull,
                                          ^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:574:48: Error: Getter not found: 'solidFontAwesomeLogoFull'.
  'solidFontAwesomeLogoFull': FontAwesomeIcons.solidFontAwesomeLogoFull,
                                               ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.1.5/lib/IconPicker/Packs/FontAwesome.dart:575:49: Error: Getter not found: 'brandsFontAwesomeLogoFull'.
  'brandsFontAwesomeLogoFull': FontAwesomeIcons.brandsFontAwesomeLogoFull,
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
```


This is the full error message seemingly 3 more icons missing

**Comment by Ahmadre** [comment]
At first: sorry all for the delay. Had a lot of work here.

but good news: it was just a dependency issue here. FontAwesome Flutter is updating immediately and not all devs out there have the time to update the depending packages too.

I fixed the issue and will come with the next update very soon :)!

**Comment by Ahmadre** [comment]
Hey guys, I had to update fontAwesomeFlutter so "adobe" is no longer available. Maybe some license problems on flutter community side. But here's the new update:
[![Version](https://img.shields.io/badge/pub-v2.2.1-blue)](https://pub.dev/packages/flutter_iconpicker)

everything compiles now
