### ISSUE TITLE
cupertino_icons has newer version 1.0.0

### ISSUE THREAD

**Issue by nstrelow** [Ahmadre/FlutterIconPicker#18]
Could you check for compatibility with cupertino_icons 1.0.0 @Ahmadre ? Thanks

Error
```
Because flutter_iconpicker >=2.0.0 depends on cupertino_icons ^0.1.3 and StudyU_Designer depends on cupertino_icons ^1.0.0, flutter_iconpicker >=2.0.0 is forbidden.
```

**Comment by Ahmadre** [comment]
Thank you so much @nstrelow for raising this issue! I will fix that asap!

**Comment by Ahmadre** [comment]
@nstrelow Already fixed. But I have to investigate more for line_icons also. See here: https://github.com/galonsos/line_icons/issues/12

**Comment by Ahmadre** [comment]
New icons:
<img width="676" alt="Bildschirmfoto 2020-10-24 um 16 14 15" src="https://user-images.githubusercontent.com/18512224/97083979-068d1b80-1614-11eb-9816-146b1681d66d.png">

**Comment by Ahmadre** [comment]
New version available now: [![Version](https://img.shields.io/badge/pub-v2.2.1-blue)](https://pub.dev/packages/flutter_iconpicker)
