### ISSUE TITLE
Are other icon packs supported?

### ISSUE THREAD

**Issue by Ben-Baert** [Ahmadre/FlutterIconPicker#2]
Are other icon packs such as https://pub.dev/packages/line_awesome_icons supported? Is there an easy way to integrate these?

**Comment by Ahmadre** [comment]
Very good point @Ben-Baert! I was planning to do that for the picker. I will upgrade the package soon to do so :)

**Comment by Ahmadre** [comment]
Fixed in v1.0.0 (See supported IconPacks in Readme.md) 👍
