### ISSUE TITLE
Icon displayed does not match key

### ISSUE THREAD

**Issue by lucadev83** [Ahmadre/FlutterIconPicker#22]
The icon displayed in Dialog doesn't match with key.
Ex: key: border_bottom_outlined, icon displayed: arrow_left.
I'm using IconPack.material

![Simulator Screen Shot - iPhone 8 - 2021-05-23 at 13 52 02](https://user-images.githubusercontent.com/82050214/119272937-28f90e80-bbce-11eb-8d6a-2b752c99d6a9.png)

**Comment by Ahmadre** [comment]
Thank you so much for your issue!

I'll update the MaterialIcons in this package and that should be fixed :)

**Comment by Ahmadre** [comment]
I also know where I cause issue is. I'll fix this now

**Comment by Ahmadre** [comment]
Updating them and accessing through Icons helped:

<img width="325" alt="Bildschirmfoto 2021-05-27 um 20 21 13" src="https://user-images.githubusercontent.com/18512224/119877268-1ada2380-bf29-11eb-84c9-3ee83cdbff57.png">

**Comment by Ahmadre** [comment]
Update is coming

**Comment by lucadev83** [comment]
Waiting update...
Thanks a lot!

**Comment by Ahmadre** [comment]
Update is live. Thanks again!
