### ISSUE TITLE
Is there a way to only show baseline Icon theme?

### ISSUE THREAD

**Issue by zambetpentru** [Ahmadre/FlutterIconPicker#24]
Hi,

I just started to implement your package and it's working very well but has duplicated icons (i.e. Outlined, Round, Sharp, etc.). Is there a way to only show the baseline ones? Without say editing the Packs\Material.dart file?

**Comment by Ahmadre** [comment]
> Hi,
> 
> 
> 
> I just started to implement your package and it's working very well but has duplicated icons (i.e. Outlined, Round, Sharp, etc.). Is there a way to only show the baseline ones? Without say editing the Packs\Material.dart file?

Yes: Copy the icons you want to use for your app out of the Material Pack and add your customIconPack in the same map like you see in the Material Pack.

**Comment by Ahmadre** [comment]
You have to set the IconPack:  iconPackMode: IconPack.custom

and provide your Map<String, dynamic> customIconPack.

**Comment by zambetpentru** [comment]
Okay thank you!
