### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by zambetpentru** [Ahmadre/FlutterIconPicker#25]
Greetings,

When I upgrade to the latest master it seems that there are two icons that have been removed from the latest Flutter master?

Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.0.2/lib/IconPicker/Packs/Material.dart:1864:30: Error: Getter not found: 'door_back_rounded'.
  'door_back_rounded': Icons.door_back_rounded,

Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.0.2/lib/IconPicker/Packs/Material.dart:1869:32: Error: Getter not found: 'door_front_outlined'.
  'door_front_outlined': Icons.door_front_outlined,
                               ^^^^^^^^^^^^^^^^^^^

**Comment by Ahmadre** [comment]
> Greetings,
> 
> When I upgrade to the latest master it seems that there are two icons that have been removed from the latest Flutter master?
> 
> Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.0.2/lib/IconPicker/Packs/Material.dart:1864:30: Error: Getter not found: 'door_back_rounded'.
> 'door_back_rounded': Icons.door_back_rounded,
> 
> Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.0.2/lib/IconPicker/Packs/Material.dart:1869:32: Error: Getter not found: 'door_front_outlined'.
> 'door_front_outlined': Icons.door_front_outlined,
> ^^^^^^^^^^^^^^^^^^^

Thanks for your hint!

Actually it's a bit tricky to update now until these changes are not in stable.

I will investigate more in this and let you know :)

**Comment by nstrelow** [comment]
Why not release a pre-release version? ^^

**Comment by Ahmadre** [comment]
> Why not release a pre-release version? ^^

Thanks @nstrelow :) new version is released
