### ISSUE TITLE
Missing icons six_ft_apart

### ISSUE THREAD

**Issue by apps-auth** [Ahmadre/FlutterIconPicker#29]
In flutter 2.6.0-0.0.pre six_ft_apart icons are not available.
I tried to commit a commit to this repository but I don't have enough permission to do so so I forked to solve this problem: https://github.com/apps-auth/FlutterIconPicker/commit/4acd274dc28dac3591ec9ca6a3b6458d378da6ab

**Comment by evanzhoe** [comment]
Facing the same issue too.

**Comment by infinitysush** [comment]
Having the same issue

**Comment by popiosifcristian** [comment]
Any updates on this issue?

**Comment by hoxuanvinh1999** [comment]
Having the same issue

**Comment by hoxuanvinh1999** [comment]
> In flutter 2.6.0-0.0.pre six_ft_apart icons are not available. I tried to commit a commit to this repository but I don't have enough permission to do so so I forked to solve this problem: [apps-auth@4acd274](https://github.com/apps-auth/FlutterIconPicker/commit/4acd274dc28dac3591ec9ca6a3b6458d378da6ab)

I think you can create a pull request, I did it for you

**Comment by Ahmadre** [comment]
@hoxuanvinh1999 Thank you for your PR. I'll merge this after the comments are removed.

**Comment by Albert-Jan** [comment]
When will these changes be available on pub.dev? Currently facing compile issues. Thanks in advance!

**Comment by Ahmadre** [comment]
> When will these changes be available on pub.dev? Currently facing compile issues. Thanks in advance!

Thanks for the reminder. I'll do it right today!

**Comment by Ahmadre** [comment]
@Albert-Jan Uploaded a new version 3.0.5 :)

I tested it with latest Flutter Stable 2.8.1 and latest Dart.

Have fun!
