### ISSUE TITLE
How to add multiple icon packs to choose from?

### ISSUE THREAD

**Issue by xrayian** [Ahmadre/FlutterIconPicker#34]
I want to add all the icon packs to the widget but couldn't figure out how to do it!

**Comment by Ahmadre** [comment]
> I want to add all the icon packs to the widget but couldn't figure out how to do it!

Very good point! I'll try to add this feature asap :)

**Comment by Ahmadre** [comment]
@xrayian Just implemented that feature for you :) and updated new Version: 3.1.0.

Old api's where documented and marked as deprecated.

You can now use: `iconPackModes`.

CustomIconPacks are also respected and inlcuded 👍🏼

**Comment by xrayian** [comment]
Thanks man! 👍👍

**Comment by jlnrrg** [comment]
@Ahmadre 
Using `iconPackModes: [IconPack.custom],` still includes the material IconPack beside the custom provided.
Which is a bug I guess.

**Comment by Ahmadre** [comment]
> @Ahmadre 
> 
> Using `iconPackModes: [IconPack.custom],` still includes the material IconPack beside the custom provided.
> 
> Which is a bug I guess.

Oh yeah thanks it was because I tried to deprecate the old interface. I will delete iconPackMode completely.

**Comment by Ahmadre** [comment]
@jlnrrg fixed and published on v. 3.1.1 :)

**Comment by jlnrrg** [comment]
Sorry for questioning, but are you sure about it?
I use the version 3.1.1 and also did a `flutter clean`.

The following code is not working:
```dart

final v = await FlutterIconPicker.showIconPicker(
                        context,
                        adaptiveDialog: false,
                        showTooltips: true,
                        iconPackModes: [IconPack.custom],
                        customIconPack: Constants.icons,
                      );
```

**Comment by Ahmadre** [comment]
> Sorry for questioning, but are you sure about it? I use the version 3.1.1 and also did a `flutter clean`.
> 
> The following code is not working:
> 
> ```dart
> final v = await FlutterIconPicker.showIconPicker(
>                         context,
>                         adaptiveDialog: false,
>                         showTooltips: true,
>                         iconPackModes: [IconPack.custom],
>                         customIconPack: Constants.icons,
>                       );
> ```

I tested it with custom iconpacks, but without the `customIconPack: Constants.icons,`. Try it without. I will remove it maybe

**Comment by Ahmadre** [comment]
see also example app here, where a sample list of custom icons are provided

**Comment by Ahmadre** [comment]
> Sorry for questioning, but are you sure about it? I use the version 3.1.1 and also did a `flutter clean`.
> 
> The following code is not working:
> 
> ```dart
> final v = await FlutterIconPicker.showIconPicker(
>                         context,
>                         adaptiveDialog: false,
>                         showTooltips: true,
>                         iconPackModes: [IconPack.custom],
>                         customIconPack: Constants.icons,
>                       );
> ```

You're totally right.
![Bildschirmfoto 2022-01-04 um 03 44 22](https://user-images.githubusercontent.com/18512224/148002759-c3bb4e4f-86b3-4dce-bb8b-6c87652a7f06.png)

It was that line where `icons` where returned as default.

Fixed it now :3

**Comment by Ahmadre** [comment]
> Sorry for questioning, but are you sure about it? I use the version 3.1.1 and also did a `flutter clean`.
> 
> The following code is not working:
> 
> ```dart
> final v = await FlutterIconPicker.showIconPicker(
>                         context,
>                         adaptiveDialog: false,
>                         showTooltips: true,
>                         iconPackModes: [IconPack.custom],
>                         customIconPack: Constants.icons,
>                       );
> ```

v. 3.1.2 is uploaded. Thanks for your help :3

**Comment by jlnrrg** [comment]
Thank **you** for fixing it this fast :+1:
