### ISSUE TITLE
Spacing properties do not affect

### ISSUE THREAD

**Issue by shababhsiddique** [Ahmadre/FlutterIconPicker#41]
Spacing do not affect
Following code is used to create the picker, however the main axis and cross axis spacing properties do not affect.

` IconData? icon = await FlutterIconPicker.showIconPicker(
                                    context,
                                    adaptiveDialog: false,
                                    iconSize: 25,
                                    crossAxisSpacing: 30,
                                    mainAxisSpacing: 30,                                    
                                    title: const Text("Select an icon") ,                                    
                                    barrierDismissible: false,                                    
                                    constraints: BoxConstraints(
                                      maxHeight: 700,
                                      maxWidth: 340,
                                      minWidth: 320,
                                    ),
                                    iconPackModes: [IconPack.fontAwesomeIcons],
                                );
                                if(icon!= null) {
                                  _categoryFormController.setIcon(icon);
                                }`

<img width="314" alt="image" src="https://user-images.githubusercontent.com/7587873/153742304-0235a851-3168-4080-85ff-e95ffe8d30ca.png">

**Comment by Ahmadre** [comment]
Thank you for your hint.

Fixed in Version 3.2.1.
