### ISSUE TITLE
Way to Exclude Packs

### ISSUE THREAD

**Issue by dedvalson** [Ahmadre/FlutterIconPicker#46]
Great Package.

I noticed that when building for web this package incresed the size of of my overall output by nearly 1 MByte. Is there an easy way (other than forking) to exclude the standard packs? I only need my own custom icons.

Thanks,

Don

**Comment by Ahmadre** [comment]
> Great Package.
> 
> I noticed that when building for web this package incresed the size of of my overall output by nearly 1 MByte. Is there an easy way (other than forking) to exclude the standard packs? I only need my own custom icons.
> 
> Thanks,
> 
> Don

Thank you so much for your hint!

You're totally right...I will investigate how to do that. I can't promise when, but we should tackle that :3 ❤️

**Comment by nicolaspernoud** [comment]
It should be nice to be able to keep only normal or rounded icons at least...

**Comment by Ahmadre** [comment]
One little update to this @nicolaspernoud and @dedvalson 

Icons are now separated.

Regards Building an App via Flutter there're 2 ways as I know to strip out unused Dart Files (Imports):

1. https://docs.flutter.dev/perf/deferred-components (only Android + Web)
2. Using `build_runner`or generate only those files which are used by the developer in their Flutter project.

I will investigate more into the second way.

**Comment by nicolaspernoud** [comment]
Hello, Thanks for the update.
As I understand, for now, we can display only rounded icons (for example) but the normal ones won't be stripped ?

**Comment by Ahmadre** [comment]
> Hello, Thanks for the update.
> 
> As I understand, for now, we can display only rounded icons (for example) but the normal ones won't be stripped ?

Exactly.

I'm doing some research now (when I got time) and looking for s solution for stripping out unused dart files.

Meanwhile if someone has a solution one can always open a PR and we will maybe get sooner an update 🙂.

This topic definetly has priority.

**Comment by Ahmadre** [comment]
I finished it and implemented a solution @nicolaspernoud and @dedvalson 😸 

See linked PR on how big/small the app size is before and after.

I will release a new version today!
