### ISSUE TITLE
Build fails in Flutter 3.0

### ISSUE THREAD

**Issue by ameenvga** [Ahmadre/FlutterIconPicker#47]
It was working fine. Today I just updated my flutter to Flutter 3.0.
Now, when I` flutter run` this error shows and build fails. 
```

/C:/Users/ameen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart(1230,25): error G75B77105: Member not found: 'class__sharp'. [C:\posterapp\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/ameen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart(1231,27): error G75B77105: Member not found: 'class__rounded'. [C:\posterapp\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/ameen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart(1232,28): error G75B77105: Member not found: 'class__outlined'. [C:\posterapp\build\windows\flutter\flutter_assemble.vcxproj]

/C:/Users/ameen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/iconPicker.dart(47,20): warning G1E0FE241: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [C:\posterapp\build\windows\flutter\flutter_assemble.vcxproj]
```

**Comment by internelp** [comment]
Same problem.

**Comment by ghengx** [comment]
any updates for the fix?

**Comment by ghengx** [comment]
> > any updates for the fix?
> 
> I provided the fix, but the pull request is not approved yet.

Thanks mate

**Comment by DewminaUdayashan** [comment]
For now open YOUR_PC/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart file and search and comment the lines that contains,
**class_sharp, class_rounded, class_outlined** and rebuild the project.

**Comment by Leomhl** [comment]
Same problem here with flutter 3.0.3

**Comment by TomasWard1** [comment]
Same problem

**Comment by TomasWard1** [comment]
@Leomhl  can't seem to find that directory, can you point me in the right direction? I'm with a mac

**Comment by ObjectiveCalendar** [comment]
> For now open YOUR_PC/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart file and search and comment the lines that contains, **class_sharp, class_rounded, class_outlined** and rebuild the project.

this works well to fix the problem at least in local, but I don't think it will be the case in production.

**Comment by razfazz** [comment]
is there a better fix for now?

**Comment by jpv123** [comment]
@Ahmadre Can you please help us with this? It should be an easy fix :)

**Comment by Ahmadre** [comment]
It's fixed and published: [![Version](https://img.shields.io/pub/v/flutter_iconpicker.svg)](https://pub.dev/packages/flutter_iconpicker)

**Comment by justinBrrict** [comment]
This is still happening to me even though I am already using v3.2.2

/C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25632:21: Error: Member not found: 'whatsapp'.
  'whatsapp': Icons.whatsapp,
                    ^^^^^^^^
/C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25635:27: Error: Member not found: 'whatsapp_sharp'.
  'whatsapp_sharp': Icons.whatsapp_sharp,
                          ^^^^^^^^^^^^^^
/C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25638:29: Error: Member not found: 'whatsapp_rounded'.
  'whatsapp_rounded': Icons.whatsapp_rounded,
                            ^^^^^^^^^^^^^^^^
/C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25641:30: Error: Member not found: 'whatsapp_outlined'.
  'whatsapp_outlined': Icons.whatsapp_outlined,
                             ^^^^^^^^^^^^^^^^^

can anyone help?

**Comment by Ahmadre** [comment]
> This is still happening to me even though I am already using v3.2.2
> 
> /C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25632:21: Error: Member not found: 'whatsapp'. 'whatsapp': Icons.whatsapp, ^^^^^^^^ /C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25635:27: Error: Member not found: 'whatsapp_sharp'. 'whatsapp_sharp': Icons.whatsapp_sharp, ^^^^^^^^^^^^^^ /C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25638:29: Error: Member not found: 'whatsapp_rounded'. 'whatsapp_rounded': Icons.whatsapp_rounded, ^^^^^^^^^^^^^^^^ /C:/Users/supre/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_iconpicker-3.2.2/lib/IconPicker/Packs/Material.dart:25641:30: Error: Member not found: 'whatsapp_outlined'. 'whatsapp_outlined': Icons.whatsapp_outlined, ^^^^^^^^^^^^^^^^^
> 
> can anyone help?

its fixed :)
