### ISSUE TITLE
Icons missing, can't compile app

### ISSUE THREAD

**Issue by user97116** [Ahmadre/FlutterIconPicker#50]
flutter_iconpicker: 3.1.4+1

```
.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart:1231:27: Error: Member not found: 'class__rounded'.
  'class__rounded': Icons.class__rounded,
                          ^^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart:1232:28: Error: Member not found: 'class__outlined'.
  'class__outlined': Icons.class__outlined,
```

**Comment by TomasWard1** [comment]
Same here:
`../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart:1230:25: Error: Member not found: 'class__sharp'.
      'class__sharp': Icons.class__sharp,
                            ^^^^^^^^^^^^
    ../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart:1231:27: Error: Member not found: 'class__rounded'.
      'class__rounded': Icons.class__rounded,
                              ^^^^^^^^^^^^^^
    ../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.4+1/lib/IconPicker/Packs/Material.dart:1232:28: Error: Member not found: 'class__outlined'.
      'class__outlined': Icons.class__outlined,`

**Comment by gabrc52** [comment]
```
: Error: Member not found: 'class__sharp'.
../…/Packs/Material.dart:1230
  'class__sharp': Icons.class__sharp,
                        ^^^^^^^^^^^^
: Error: Member not found: 'class__rounded'.
../…/Packs/Material.dart:1231
  'class__rounded': Icons.class__rounded,
                          ^^^^^^^^^^^^^^
: Error: Member not found: 'class__outlined'.
../…/Packs/Material.dart:1232
  'class__outlined': Icons.class__outlined,
```

Can confirm. The other package suffers from a similar issue.

**Comment by Ahmadre** [comment]
Fixed it.

I will update Material Icons to latest stable icons.

**Comment by Ahmadre** [comment]
Published new version: [![Version](https://img.shields.io/pub/v/flutter_iconpicker.svg)](https://pub.dev/packages/flutter_iconpicker)
