### ISSUE TITLE
Lib not compatible with the flutter stable track since ages

### ISSUE THREAD

**Issue by DivineThreepwood** [Ahmadre/FlutterIconPicker#58]
I am curious if this lib is still supported or just an outdated artifact? We always get in trouble after upgrading flutter. Last time we could establish a stable track compatibility by linking against your "hotfix" branch that is still not merged.

Is there any change that the flutter stable track compatibility is established again in near future?

**Comment by azimuthdeveloper** [comment]
I forked it and pushed a new version to pub dev, spoke about it here: https://github.com/Ahmadre/FlutterIconPicker/issues/59#issuecomment-1547780159

**Comment by Ahmadre** [comment]
Since ages is not true honestly (be nice and see Changelog date).

This is OpenSource (just a reminder).

But as i went through actual changes: a new version is published today.
