### ISSUE TITLE
Expose search logic

### ISSUE THREAD

**Issue by xunafay** [Ahmadre/FlutterIconPicker#61]
I think it would be nice if the search logic were to be exposed for overwriting.
https://github.com/Ahmadre/FlutterIconPicker/blob/9db0280c1a432c37ace0ab6e277b8b2c85831d99/lib/IconPicker/searchBar.dart#L43

e.g.
```dart
// signature
bool Function(String search, String icon)

FlutterIconPicker.showIconPicker(
 ...
 searchCompare: (search, icon) => search.toLowerCase().contains(icon.replaceAll('_', ' ').toLowerCase())
 ...
);
```
Here I simply added a string replace but I'd like to use a fuzzy search library like [fuzzywuzzy](https://pub.dev/packages/fuzzywuzzy)

**Comment by Ahmadre** [comment]
Interesting 🤔 thanks for mentioning. I will open a PR and tag you for review, if it fits your needs. I think this would be a neat feature (And sorry for the late response).

**Comment by Ahmadre** [comment]
@xunafay Finished:

Example:

<img width="644" alt="Bildschirmfoto 2024-02-08 um 21 04 57" src="https://github.com/Ahmadre/FlutterIconPicker/assets/18512224/8bc808ca-a5d2-4382-ae7a-a11b9d4354c0">

Preview:

<img width="685" alt="Bildschirmfoto 2024-02-08 um 21 04 52" src="https://github.com/Ahmadre/FlutterIconPicker/assets/18512224/831064cf-c3c9-4922-b5ba-e61a8a48ad51">

I will merge it after I've updated the docs :)
