### ISSUE TITLE
Sharp, rounded, outlined not supported but still appears

### ISSUE THREAD

**Issue by Zerak630** [Ahmadre/FlutterIconPicker#62]
Hey there,

I have an issue with the _IconPack.material_ : it's written in your readme file that Sharp, rounded, outlined are not supported, however they still appears in the list as shown below.
![image](https://github.com/Ahmadre/FlutterIconPicker/assets/48765511/e1459e57-ded3-4b9e-a462-3015f7d8e1e3)

I would suggest to split the Material.dart file in four different files and be able to add them as you want.

**Comment by Ahmadre** [comment]
Thank you for your isse.

Yeah, I know that this is still a required feature, after Flutter mixed up all Icons together into the icons.dart file in Flutter Framework.

It's honestly a lot of work, but I try to write a script to filter out the icons and seperate them into seperate dart files to be loaded seperatly.

**Comment by Ahmadre** [comment]
Finished.

I will release today another version @Zerak630 .

**Comment by Zerak630** [comment]
Hey, thank you for your work ! I'll update as soon as you publish it :)

**Comment by Ahmadre** [comment]
> Hey, thank you for your work ! I'll update as soon as you publish it :)

It's already published :)
