### ISSUE TITLE
Icons are not showing

### ISSUE THREAD

**Issue by jyyoooo** [Ahmadre/FlutterIconPicker#67]
Im getting No results for: message by default when i open the picker and even when i search i cant seem to find any icons.

 onTap: () async => selectedIcon = await showIconPicker(
                      showSearchBar: false,
                      iconPackModes: [IconPack.allMaterial, IconPack.cupertino],
                      searchComparator: (String search, IconPickerIcon icon) =>
                          search.toLowerCase().contains(
                              icon.name.replaceAll('_', ' ').toLowerCase()) ||
                          icon.name
                              .toLowerCase()
                              .contains(search.toLowerCase()),
                      iconPickerShape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                      context,
                      title: const Text('Select badge icon')),
                      
                      am i missing something?

**Comment by PhanithNoch** [comment]
Same

**Comment by StevePhuc** [comment]
after done this and restart then icon showing https://github.com/Ahmadre/FlutterIconPicker/issues/66#issuecomment-1978556008

**Comment by luckygogreen** [comment]
> after done this and restart then icon showing [#66 (comment)](https://github.com/Ahmadre/FlutterIconPicker/issues/66#issuecomment-1978556008)
Still not work ,is there anything we need to do ?

**Comment by Ahmadre** [comment]
Fixed some bugs by upgrading dcli package
