### ISSUE TITLE
Flutterflow build error

### ISSUE THREAD

**Issue by leobewater** [Ahmadre/FlutterIconPicker#68]
Hi, 

Thank you so much for creating this package. 

I'm using FlutterFlow and implemented the package into my app. It works great on all the testing devices but when I build the apk, it's showing this error. I'm using v3.2.4 since the latest version has a package conflict with FlutterFlow. Any ideas why it's showing this error? Much appreciated your help!

This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/[user]/.pub-cache/hosted/pub.dev/flutter_iconpicker-3.2.4/lib/Serialization/iconDataSerialization.dart:76:16
Target aot_android_asset_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.

**Comment by Ahmadre** [comment]
Yes: when you build your apk you need to set in your `flutter build ...` command the flag: `--no-tree-shake-icons`
