### ISSUE TITLE
getBasePackagePath() function not working for spaces in package path

### ISSUE THREAD

**Issue by skdevelopment** [Ahmadre/FlutterIconPicker#71]
Package path retrieves spaces as a %20 and doesn't allow the copy function to work. 

I had to update the function to the following:

Future<String> getBasePackagePath() async {
  final packageUri =
      Uri.parse('package:flutter_iconpicker/flutter_iconpicker.dart');
  final packagePath = (await Isolate.resolvePackageUri(packageUri));
  String resultPath = path.dirname(packagePath!.path.replaceAll('lib', ''));
  if (Platform.isWindows) {
    resultPath = resultPath
        .replaceAll(Platform.pathSeparator, '/')
        .replaceFirst('/', '')
        .replaceAll('%20', ' ');
  }
  return resultPath;
}

**Comment by Ahmadre** [comment]
Thanks for the hint.

I could reproduce the issue on Windows.

But just an information for you: you should NEVER create empty strings in your paths. No matter if you work on Flutter projects or any other projects.

I will fix this in the next release.

**Comment by Ahmadre** [comment]
Published new version: 3.4.6
