### ISSUE TITLE
On WEB not see icons list after published on server

### ISSUE THREAD

**Issue by Paroca72** [Ahmadre/FlutterIconPicker#72]
Hello,

After published the WEB application on server I not see the icons inside dialog list.
Same effect when not run on local the command
dart run flutter_iconpicker:generate_packs --packs <material,cupertino,..>

Thanks
Sam

**Comment by Ahmadre** [comment]
After running:

```bash
dart run flutter_iconpicker:generate_packs --packs cupertino

Building package executable...
Built flutter_iconpicker:generate_packs.
🛠️  Start generating Packs
📦 Generated cupertino IconPack
✅ Finished generating Packs
```

I can successfully run `example` project on Web:

![image](https://github.com/Ahmadre/FlutterIconPicker/assets/18512224/e843ec8d-32d0-43d6-bd41-8d3677d8e075)

Using latest Flutter 3.22.2.

Please provide which Flutter Version and package version you use.
