### ISSUE TITLE
Preselected Icon when open the Icon picker

### ISSUE THREAD

**Issue by MahmoudH96** [Ahmadre/FlutterIconPicker#73]
It would be very nice to have within the API-Reference a new attribute called "selectedIcon" which when populated, then if the user opens the icon picker he/she will automatically see this icon highlighted (and scrolled to its location)

**Comment by Ahmadre** [comment]
Implementation finished. I will deploy another version now.

**Comment by Ahmadre** [comment]
New Version is now online.
