### ISSUE TITLE
Cannot generate multiple icon packs

### ISSUE THREAD

**Issue by programotuojes** [Ahmadre/FlutterIconPicker#82]
3.6.4 breaks multiple icon pack generation. And since previously generated icons are cleared at every run, running `flutter_iconpicker:generate_packs` several times with different packs also doesn't work.

```console
$ flutter pub run flutter_iconpicker:generate_packs --packs=fontAwesomeIcons,lineAwesomeIcons,roundedMaterial
Deprecated. Use `dart run` instead.
Building package executable... (3.7s)
Built flutter_iconpicker:generate_packs.
Unhandled exception:
FormatException: "fontAwesomeIcons,lineAwesomeIcons,roundedMaterial" is not an allowed value for option "packs".
#0      Parser._validate (package:args/src/parser.dart:311:21)
#1      Parser._validateAllowed (package:args/src/parser.dart:349:5)
#2      Parser._setOption (package:args/src/parser.dart:320:7)
#3      Parser._handleLongOption (package:args/src/parser.dart:278:9)
#4      Parser._parseLongOption (package:args/src/parser.dart:264:12)
#5      Parser.parse (package:args/src/parser.dart:86:11)
#6      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#7      main (file:///home/gustas/.pub-cache/hosted/pub.dev/flutter_iconpicker-3.6.4/bin/generate_packs.dart:50:34)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by Ahmadre** [comment]
> 3.6.4 breaks multiple icon pack generation. And since previously generated icons are cleared at every run, running `flutter_iconpicker:generate_packs` several times with different packs also doesn't work.
> 
> ```
> $ flutter pub run flutter_iconpicker:generate_packs --packs=fontAwesomeIcons,lineAwesomeIcons,roundedMaterial
> Deprecated. Use `dart run` instead.
> Building package executable... (3.7s)
> Built flutter_iconpicker:generate_packs.
> Unhandled exception:
> FormatException: "fontAwesomeIcons,lineAwesomeIcons,roundedMaterial" is not an allowed value for option "packs".
> #0      Parser._validate (package:args/src/parser.dart:311:21)
> #1      Parser._validateAllowed (package:args/src/parser.dart:349:5)
> #2      Parser._setOption (package:args/src/parser.dart:320:7)
> #3      Parser._handleLongOption (package:args/src/parser.dart:278:9)
> #4      Parser._parseLongOption (package:args/src/parser.dart:264:12)
> #5      Parser.parse (package:args/src/parser.dart:86:11)
> #6      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
> #7      main (file:///home/gustas/.pub-cache/hosted/pub.dev/flutter_iconpicker-3.6.4/bin/generate_packs.dart:50:34)
> #8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
> #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> ```

Oh thanks! Fixed!

**Comment by Ahmadre** [comment]
Version: 3.6.5 is online now.
