### ISSUE TITLE
 Invalid font issues on iOS

### ISSUE THREAD

**Issue by SethuSenthil** [Ahmadre/FlutterIconPicker#85]
Whenever I upload the binary to Appstore Connect it gets auto rejected with the following issue:

Please correct the following issues and upload a new binary to App Store Connect:

ITMS-90853: Invalid font - There was an error validating the font named 'FontAwesome6Free-Solid' at 'Runner.app/Frameworks/App.framework/flutter_assets/packages/flutter_iconpicker/fonts/fa-solid-900.ttf'. ‘glyf’ table instructions.

@RayHughes has said that "[This appears to be related to the new Font Menu functionality in iOS 18. I'm assuming things changed in the backend when the iPhone 16 was announced." ](https://github.com/oblador/react-native-vector-icons/issues/1658#issuecomment-2345043446)

**Comment by Ahmadre** [comment]
Thank you so much for your contribution!

**Comment by Ahmadre** [comment]
New version: 4.0.1 is uploaded including updated FontAwesome generated Icon models :)
