### ISSUE TITLE
Dont show any icons anymore at least with flutter 3.24.5

### ISSUE THREAD

**Issue by KlausJuhantalo** [Ahmadre/FlutterIconPicker#89]
Github example has same issue
Dont show any icons anymore at least with flutter 3.24.5

**Comment by Ahmadre** [comment]
It works without any problems! This has nothing to do with the Flutter version!

![image](https://github.com/user-attachments/assets/1cbc08d1-5bf1-44de-9ade-87d015f94b1a)

PLEASE READ THE README! 

I wrote it multiple times in the Readme!

**Comment by KlausJuhantalo** [comment]
Yes, sorry.. this fixes: dart run flutter_iconpicker:generate_packs --packs <material,cupertino,..>
